language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
before_install:
    - go get github.com/daviddengcn/go-colortext
script:
    - go build
    - ./t/test.sh
    - go test -v ./ast/util
    - ./anko ./_example/scripts/term.ank

